version: '3'
services:
  client:
    image: '${DOCKER_CLIENT_IMAGE}'
    restart: always
    ports:
      - 3000:3000
    environment:
    - SERVER_URL=${SERVER_URL:-ws://192.168.0.100:3000} 
    - CAMERA_URL=${CAMERA_URL:-http://192.168.0.103:81/stream} 
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883   
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log  
    restart: always

  influxdb:
    image: influxdb:2.3-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment: 
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER:-nakuja}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-987654321}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-nakuja}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-telemetry}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-myToken}      
    restart: always
  telegraf:
    image: telegraf:1.20-alpine
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-nakuja}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-telemetry}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-myToken}      
    depends_on:
      - mosquitto
      - influxdb
      - client
    restart: always
  
volumes:
  influxdb2:
  mosquitto-data:
  mosquitto-log:
